spring:


  profiles:
    active: local
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=login
    username: sa
    password: root
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: none
